[build]
publish = "public"
#command = "hugo" #サイト上で個別に指定

[context.production.environment]
HUGO_VERSION = "0.70.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"
RUBY_VERSION = "2.6.2" #build時に2.3.6をinstallし始める問題に対応
NODE_VERSION = "10"
GO_VERSION = "1.14"
PHP_VERSION = "7.4"

[context.split1]
command = "hugo --enableGitInfo"

[context.split1.environment]
HUGO_VERSION = "0.70.0"
HUGO_ENV = "production"
RUBY_VERSION = "2.6.2" #build時に2.3.6をinstallし始める問題に対応
NODE_VERSION = "10"
GO_VERSION = "1.14"
PHP_VERSION = "7.4"

[context.deploy-preview]
command = "hugo --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.70.0"
RUBY_VERSION = "2.6.2" #build時に2.3.6をinstallし始める問題に対応
NODE_VERSION = "10"
GO_VERSION = "1.14"
PHP_VERSION = "7.4"

[context.branch-deploy]
command = "hugo -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.70.0"
RUBY_VERSION = "2.6.2" #build時に2.3.6をinstallし始める問題に対応
NODE_VERSION = "10"
GO_VERSION = "1.14"
PHP_VERSION = "7.4"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"

[[redirects]]
from = "/pdf/jsp/2/1/2_1_01yokoro.pdf"
to = "/pdf/jsp/2/1/2_1_03yokoro.pdf"
status = 301
force = true


[[redirects]]
from = "/analytical_machanics"
to = "/analytical_mechanics"
status = 301
force = true


[[redirects]]
from = "/pdf/jsp/3/1/3_1pre_01yokoro.pdf"
to = "/pdf/jsp/3/1/3_1_03yokoro.pdf"
status = 301
force = true
